### ISSUE TITLE
IGPU only variant 

### ISSUE THREAD

**Issue by ludalex** [liaojack8/ASUS-Z390F-Hack#1]
Hello there, 

I have roughly your same setup, minus the AMD dGPU. I've tried to use your EFI folder with no success, with the only difference in the bios settings with: 

Primary Display: ~PCIE~ -> CPU
iGPU Monitor: ~Enabled~ -> Disabled

Unfortunately it doesn't boot. Are there any changes I need to apply to your configuration if I just want to use my HD 630 IGPU?

**Comment by liaojack8** [comment]
Hello Hackintosher,
First, I need to know the detail of your setup to analyze what is the problem in EFI for your case.
Second, base on you want to use UHD630, I suggest change SMBIOS to imacpro1,1, and delete the item named "Intel UHD Graphics 630 (Desktop 8 Series)" in DeviceProperties, then try to boot MacOS installer.
btw, owing to some reason, I haven't use my EFI to boot or install catalina

**Comment by liaojack8** [comment]
@ludalex Hi, I have been updated the EFI that can boot and install Catalina.
So, please refer my latest release. The modify items to let EFI suitable for your devices same as I reply last time.
The most important is checking your bios version and settings.

**Comment by ludalex** [comment]
Hey @liaojack8 thanks a lot. It seems though that you forgot to commit your `EFI` folder?

**Comment by liaojack8** [comment]
@ludalex check my release please!

**Comment by ludalex** [comment]
I did and thank you so much, so far it's the only build for the Asus Strix Z390-F that has sleep/wake working under Catalina 10.15.6 and with iGPU only! (I've also tried [this](https://github.com/leto1210/z390-Hack) and [one based on this one](https://www.tonymacx86.com/threads/cant-reach-installer-clover-reboots-help-needed-asus-rog-strix-z390-f-9700k-integrated-graphics.288742/#post-2154946) but neither have sleep/wake working).

The only thing I noticed is that compared to the two above the boot process of yours is about 20s longer, would you happen to know why?

**Comment by liaojack8** [comment]
Congrats! I'm glad to help you out.
I spent much time to complete this repo, to help people build hackintosh successfully.
About your question, I wanna know your calculated start time and end time.
I build dual-boot desktop, so I set 10s time limit for select boot partition, you can set for yourself in Misc>Boot>Timeout.
That's weird if 20s from click power button to shown the OC picker menu.

**Comment by ludalex** [comment]
I'm talking about the actual boot time - after the Apple logo appears - not the time it takes from powering on to show the OC picker (that is very fast).
It's considerably longer than other builds I've tried and I was wondering if you happen to know why that's the case (maybe a setting, a kext or patch that increases it).

**Comment by liaojack8** [comment]
Okay, I'll check this problem.

**Comment by ludalex** [comment]
I've managed to make it fast by removing the block in DeviceProperties which referenced your AMD GPU. I have an NVIDIA 2080ti so I had to disable that (by adding `-wegnoegpu` in boot-args).

It is now super fast and I have sleep/wake working! Thanks again.

**Comment by liaojack8** [comment]
Thanks for your sharing.
I test my boot time, from powering to show OC picker takes for about 20s. I think it's slowly than yours, right?

**Comment by esmith1966** [comment]
Has anyone tested the EFI with iGPU only on Big Sur?

Does that simply involve removing the graphics card from the system?

**Comment by liaojack8** [comment]
Why you ask this...I guess you using nvidia graphics card, right?

**Comment by esmith1966** [comment]
No…

Simply if I just want to use the cpu graphics instead of buying an amd graphics card like if I want to run a file server or FileMaker database server

I did test it without my RX-580 card and the graphics for scrambled 

I have some less expensive nvidia cards that apple still
supports that I will test tomorrow

**Comment by liaojack8** [comment]
Well...
Again... You should visit [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html).
First, remove `PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)` from `DeviceProperties` in config file
Next, switch to `PciRoot(0x0)/Pci(0x2,0x0)`, delete every elements in dict, and add elements like the table below
|Key|Type|Value|
|----|----|----|
|AAPL,ig-platform-id|Data|07009B3E|
|framebuffer-patch-enable|Data|01000000|
|framebuffer-stolenmem|Data|00003001|

**Comment by liaojack8** [comment]
hey guys, I already update the config file for both iGPU user and dGPU user, please visit my release page, `OC066`
