### ISSUE TITLE
Big Sur compatibility

### ISSUE THREAD

**Issue by ludalex** [liaojack8/ASUS-Z390F-Hack#2]
Any chance you managed to get this motherboard to work with Big Sur 100%?
I almost did, the only issue I have is that it fails to wake from sleep. I'm using iGPU only.

**Comment by liaojack8** [comment]
Sorry about that, update to BigSur isn't in my plan so far.

**Comment by liaojack8** [comment]
@ludalex, I release EFI file using OpenCore 0.6.3 yesterday, It can upgrade to 11.0.1 form 10.15.7 by OTA.
If you do a full clean install, I think that EFI file can boot and install success.
How it works? still testing, but I guess it's 100% compatible, it works great so far.
For my case, booting time even less than 10.15.7 on OC063, just spent 5~10 s after the Apple logo appears, and shows login screen.

**Comment by ludalex** [comment]
Great news, thanks for the heads up!

I'm curious to know if you have Sleep/Wake working fine with Big Sur + OC 0.6.3 because when I tested it with 0.6.1 it wasn't waking up correctly for me.

Anyway, I will test it as soon as I can and let you know.

**Comment by liaojack8** [comment]
Well..unfortunately, I have Sleep/Wake working problem, too, I still finding the solution for it.
btw, If you have video playing problem like youtube 4k/8k video on safari, netflix 4k or apple tv plus,  you can try to change SMBIOS to Mac Pro.

**Comment by sy2nyk** [comment]
I have sleep/wake working on z380-f. 
[config.plist.zip](https://github.com/liaojack8/ASUS-Z390F-Hack/files/5602603/config.plist.zip)

**Comment by liaojack8** [comment]
Thanks to @sy2nyk , I fix sleep/wake working problem by referring to his config file(I guess it's same as my config file on Catalina), and I also add `dart=0` to `boot-args` in config file.
I already release the EFI support sleep/wake.

**Comment by ludalex** [comment]
Great! What did you actually change? There is no commit that patches `config.plist`, can maybe add it from the release you made?

**Comment by liaojack8** [comment]
@ludalex 
For some reasons, I'll not add the efi folder to the repository, and I've already noted my changes in the release description.
Maybe I will add config.plist to the repository in the future, I'm considering this matter, thank you for your suggestions.
