### ISSUE TITLE
你好 我的 CPU 是9900K 请问怎么修改配置

### ISSUE THREAD

**Issue by wujunze** [liaojack8/ASUS-Z390F-Hack#3]
你好 我的 CPU 是9900K 请问怎么修改配置

**Comment by liaojack8** [comment]
@wujunze 沒有獨顯的嗎

**Comment by wujunze** [comment]
有的

CPU 9900K 
主板 华硕 ROG-Z390 F 
硬盘 西数 SN750 1T 
显卡 蓝宝石超白金 RX580 2304SP 8G 满血版 
蓝牙网卡二合一: BCM943602CS

**Comment by liaojack8** [comment]
@wujunze 那麼不需要修改的，可以直接使用，請注意bios版本以及設定項

**Comment by wujunze** [comment]
> @wujunze 那麼不需要修改的，可以直接使用，請注意bios版本以及設定項

好的 谢谢
请问 BIOS 设置是 导入 仓库中的 txt 文件吗

**Comment by liaojack8** [comment]
@wujunze 請參考中文說明文檔 [https://github.com/liaojack8/ASUS-Z390F-Hack/blob/master/README_cht.md](url)

**Comment by wujunze** [comment]
OK 谢谢
