### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by esmith1966** [liaojack8/ASUS-Z390F-Hack#4]
What do we change so that the Installer Language is English...

When I boot to the Big Sur installer, the screen is in Chinese...

What is the config.sys modification that needs to be made?

**Comment by liaojack8** [comment]
You should visit [here](https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#nvram) to understand fully configuration about opencore.
![image](https://user-images.githubusercontent.com/23449425/110193756-d468b180-7e70-11eb-82c8-5dc22cb9af09.png)

**Comment by esmith1966** [comment]
OK... figured it out...
