### ISSUE TITLE
no install drives

### ISSUE THREAD

**Issue by esmith1966** [liaojack8/ASUS-Z390F-Hack#6]
![IMG_5178](https://user-images.githubusercontent.com/49659346/129831858-96279f00-9314-4d15-8dd6-a48fae448ad4.jpeg)
Attempting to install Big Sur and/or Monterey...

In the OpenCore boot screen, only EFI and the nvram icons appear.

I dont see the install drive...

Uploading a screen shot of the screen...

How do I fix this?

**Comment by liaojack8** [comment]
In config.plist, you can use OCC to change scan policy to fix this problem.

**Comment by liaojack8** [comment]
Misc-Security-Sacn Policy

**Comment by esmith1966** [comment]
OK... that is now fixed...

BUT getting message of "Your mac needs a firmware update in order to install to this volume... select a Mac OS Extended Volume..."

**Comment by esmith1966** [comment]
"disable customsmbiosguid" ???

This didn't work...

**Comment by liaojack8** [comment]
I haven't face this error message, what's MB you used? Same as asus rog z390-f?

How about install in Mac OS Extended (Journaled) formatted partition, re-format your drive and try it again.

**Comment by esmith1966** [comment]
of course my board is asus rog z390-f
downloaded another EFI to see if the problem exists with that EFI...
trying to compare the config.sys files...

**Comment by esmith1966** [comment]
your EFI is able to boot OS when its already installed...
issue when installing clean install from USB

**Comment by liaojack8** [comment]
Pretty sure can clean install from USB installer.
For BigSur installer, can boot to screen that select target partition, I’ll test clean install when I feel free, for Monterey installer, can boot and install os completely.
